### PR TITLE
DBZ-1052 Emit tx BEGIN/END messages

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-1052

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, will the old connector version (1.1.0.Alpha1) gracefully handle this, i.e. just ignore the new events unknown to it? And do we get these events from wal2json, too?

**Comment by jpechane** [comment]
@gunnarmorling No, we will ned to docuemtn the need to first upgrade the connector and then upgrade the database. There is no technical way to support other way around.

We don't get the events from wal2json as we get the whole transaction as a single message (either chunked or not). In this case we artifically emit BEGIN and END in connector code when processing fo the big message starts and finishes

**Comment by gunnarmorling** [comment]
> first upgrade the connector and then upgrade the database.

Oh, I think that's a problem. It wasn't like that for other similar changes in the past. And reverting the database change in case of a problem is more bothersome than reverting the connector version.

> There is no technical way to support other way around.

Why is that? I just looked at the code and I think in fact we're to strict by failing in case of unexpected operations. Instead, such event should be ignored. `PgProtoReplicationMessage#getOperation()` could return a new enum constant `UNKNOWN` which will be bubbled up and eventually ignored. You could even enhance the switch and add 3 and 4 (the numbers, no constants), so to log a warning about the mismatch of connector/plugin upon first encounter.

**Comment by jpechane** [comment]
@gunnarmorling But you have just desribed the problem! `1.1.0.Alpha1` contains the code that throws exceptions on unkown message types. So we cannot deploy the new database plugin first as it will emit the messages that are not know to the old connector. And while we can handle this in the code for handling such situation in the future we cannot fix this for upgrades from currently deployed versions.

**Comment by gunnarmorling** [comment]
Yes, just realized that, too :-( So there's no way around it this time indeed. But let's change the code to be more lenient, so to avoid similar issues in the future.

**Comment by jpechane** [comment]
@gunnarmorling This change must be done in a separate issue/PR as it certainly must be backported into 1.0 as well.

**Comment by gunnarmorling** [comment]
> This change must be done in a separate issue/PR

PR, yes. And we should get that one into master and 1.0 before this one here.

**Pull request merged**
