### PR TITLE
DBZ-1367 Adding marker value when ProtoBuf messages contain an unchanged TOAST column value

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.jboss.org/browse/DBZ-1367

### CODE REVIEW

**Comment by jamestut** [comment]
A TOASTed column will have its `datum_missing` set, whereas a nulled column behaves as before (empty `datum` field), right?
I have tested this PR and I am perfectly fine with this change.

**Comment by gunnarmorling** [comment]
> A TOASTed column will have its datum_missing set, whereas a nulled column behaves as before (empty datum field), right?

Yes, exactly. For an unchanged TOASTed column `datum_missing` will be `true`. A nulled column (TOASTed or not) will have the `datum` field empty.

Btw. I realized that we incorrectly expose the value of an unchanged TOASTed column in the before state. That's not something we can reliably do as this value is not part of the WAL, so we have to fetch it out of bands and might retrieve the wrong value in case of concurrent updates. I've logged [DBZ-1368](https://issues.jboss.org/browse/DBZ-1368) for fixing this (by also setting `datum_missing` to `true` in the before state in this case).

**Comment by gunnarmorling** [comment]
@jpechane, I *think* this is the case, but would be nice if you confirmed: the change is compatible in both directions; i.e. both of the following scenarios should be supported:

* old server-side decoderbufs plug-in and new connector
* new server-side decoderbufs plug-in and old connector

In the second case, what's the behavior exposed to message consumers then for an unchanged TOASTed column? Will the value be null (for an optional column) or the fallback value (for a NOT NULL column)?

**Comment by jpechane** [comment]
@gunnarmorling Hi, I've just verified that it is null + fallback

**Comment by gunnarmorling** [comment]
Applied. Thanks!

**Pull request merged**
